# Generated by Django 2.0.7 on 2018-09-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20180922_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='title',
        ),
    ]
