# Generated by Django 2.0.7 on 2018-09-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='positions',
            field=models.ManyToManyField(blank=True, to='positions.Position'),
        ),
    ]
