# Generated by Django 2.0.7 on 2018-09-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
        ('recommendations', '0005_auto_20180922_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='educations',
            field=models.ManyToManyField(blank=True, to='educations.Education'),
        ),
    ]
