# Generated by Django 2.0.7 on 2018-09-23 00:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_recommendation_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='relationship',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Direct supervisor', 'Direct supervisor'), ('Coworker', 'Coworker'), ('Client', 'Client'), ('Instructor', 'Instructor'), ('Vendor', 'Vendor')], default='connection', max_length=51),
            preserve_default=False,
        ),
    ]
