# Generated by Django 2.0.7 on 2018-09-23 14:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_recommendation_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='relationship',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Direct supervisor', 'Direct supervisor'), ('Coworker', 'Coworker'), ('Client', 'Client'), ('Instructor', 'Instructor'), ('Mentor', 'Mentor'), ('Vendor', 'Vendor')], max_length=58),
        ),
    ]
