# Generated by Django 2.0.7 on 2018-09-24 12:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_auto_20180923_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
