# Generated by Django 2.0.7 on 2018-08-14 03:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
