# Generated by Django 2.0.7 on 2018-10-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority']},
        ),
    ]
