# Generated by Django 2.0.7 on 2018-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
