# Generated by Django 2.0.7 on 2018-10-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_published'),
        ('projects', '0008_auto_20181016_1237'),
        ('educations', '0002_education_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='education',
            name='references',
            field=models.ManyToManyField(blank=True, to='references.Reference'),
        ),
    ]
