# Generated by Django 2.0.7 on 2018-10-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0003_auto_20181016_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
