# Generated by Django 2.0.7 on 2018-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
