# Generated by Django 2.0.7 on 2018-09-24 13:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0005_remove_position_current'),
        ('educations', '0001_initial'),
        ('projects', '0004_auto_20180813_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('relationship', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Direct supervisor', 'Direct supervisor'), ('Coworker', 'Coworker'), ('Client', 'Client'), ('Instructor', 'Instructor'), ('Mentor', 'Mentor'), ('Vendor', 'Vendor')], max_length=58)),
                ('notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('educations', models.ManyToManyField(blank=True, to='educations.Education')),
                ('positions', models.ManyToManyField(blank=True, to='positions.Position')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project')),
            ],
        ),
    ]
