# Generated by Django 2.0.7 on 2018-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
