# Generated by Django 2.0.7 on 2018-10-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
