# Generated by Django 2.0.7 on 2018-10-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_auto_20180924_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['start_date']},
        ),
    ]
