# Generated by Django 2.0.7 on 2018-08-15 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20180814_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_date',
            field=models.DateField(),
        ),
    ]
