# Generated by Django 2.0.7 on 2018-08-15 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20180814_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
