# Generated by Django 2.0.7 on 2018-08-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_auto_20180814_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='current',
        ),
    ]
