# Generated by Django 2.0.7 on 2018-09-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0005_remove_position_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
