# Generated by Django 2.0.7 on 2018-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_published'),
        ('positions', '0006_position_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='references',
            field=models.ManyToManyField(blank=True, to='references.Reference'),
        ),
    ]
