# Generated by Django 2.0.7 on 2018-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_published'),
        ('positions', '0007_position_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
